name: Inference

on:
  workflow_call:
    inputs:
      ci_type:
        type: string
        default: 'pr'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-inf
  cancel-in-progress: true

env:
  ACTIONS_RUNNER_CONTAINER_IMAGE: 10.1.2.13:5000/llmray-build
  HTTPS_PROXY_CONTAINER: http://proxy-chain.intel.com:911
  HTTP_PROXY_CONTAINER: http://proxy-chain.intel.com:911

jobs:
  inference:
    name: inference test
    strategy:
      matrix:
        model: [ gpt-j-6b, gpt2, bloom-560m, opt-125m, mpt-7b, mistral-7b-v0.1, mpt-7b-bigdl, neural-chat-7b-v3-1 ]
        isPR:
          - ${{inputs.ci_type == 'pr'}}

        exclude:
          - { isPR: true }

        include:
          - { model: "gpt-j-6b"}
          - { model: "mistral-7b-v0.1"}
          - { model: "mpt-7b-bigdl"}
          - dtuner_model: nathan0/mpt-7b-deltatuner-model
            model: mpt-7b

    runs-on: self-hosted

    defaults:
      run:
        shell: bash
    container:
      image: "$ACTIONS_RUNNER_CONTAINER_IMAGE"
      env:
        http_proxy: "$HTTP_PROXY_CONTAINER"
        https_proxy: "$HTTPS_PROXY_CONTAINER"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Determine Target
        id: "target"
        run: |
          target="inference"
          if [[ ${{ matrix.model }} == "mpt-7b-bigdl" ]]; then
            target="${target}_bigdl_cpu"
          fi
          echo "target is ${target}"
          echo "target=$target" >> $GITHUB_OUTPUT

      - name: Build Docker Image
        run: |
          if [[ ${{ matrix.model }} == "mpt-7b-bigdl" ]]; then
            DF_SUFFIX=".bigdl-cpu"
          else
            DF_SUFFIX=".cpu_and_deepspeed"
          fi
          TARGET=${{steps.target.outputs.target}}
          docker build ./ --build-arg CACHEBUST=1 --build-arg http_proxy="$HTTP_PROXY_CONTAINER" --build-arg https_proxy="$HTTPS_PROXY_CONTAINER" -f dev/docker/Dockerfile${DF_SUFFIX} -t ${TARGET}:latest && yes | docker container prune && yes
          docker image prune -f

      - name: Start Docker Container
        run: |
          TARGET=${{steps.target.outputs.target}}
          cid=$(docker ps -q --filter "name=${TARGET}")
          if [[ ! -z "$cid" ]]; then docker stop $cid && docker rm $cid; fi
          docker run -tid -v DV_MODEL_CACHE_PATH:/root/.cache/huggingface/hub -v DV_CODE_CHECKOUT_PATH:/root/llm-on-ray -e http_proxy="$HTTP_PROXY_CONTAINER" -e https_proxy="$HTTPS_PROXY_CONTAINER" --name="${TARGET}" --hostname="${TARGET}-container" ${TARGET}:latest

      - name: Start Ray Cluster
        run: |
          TARGET=${{steps.target.outputs.target}}
          docker exec "${TARGET}" bash -c "./inference/deep/start-ray-cluster.sh"

      - name: Run Inference Test
        run: |
          TARGET=${{steps.target.outputs.target}}
          if [[ ${{ matrix.model }} == "mpt-7b-bigdl" ]]; then
            docker exec "${TARGET}" bash -c "python inference/serve.py --config_file inference/models/bigdl/mpt-7b-bigdl.yaml --serve_simple"
          else
            docker exec "${TARGET}" bash -c "MODEL_TO_SERVE=\"${{ matrix.model }}\" python inference/serve.py --serve_simple"
          fi
          docker exec "${TARGET}" bash -c "python examples/inference/api_server_simple/query_single.py --num_iter 1 --model_endpoint http://127.0.0.1:8000/${{ matrix.model }}"
          docker exec "${TARGET}" bash -c "python examples/inference/api_server_simple/query_single.py --num_iter 1 --model_endpoint http://127.0.0.1:8000/${{ matrix.model }} --streaming_response"
      
      - name: Run Inference Test with Deltatuner
        if: ${{ matrix.dtuner_model }}
        run: |
          TARGET=${{steps.target.outputs.target}}
          docker exec "${TARGET}" bash -c "python inference/serve.py --config_file .github/workflows/config/mpt_deltatuner.yaml --serve_simple"
          docker exec "${TARGET}" bash -c "python examples/inference/api_server_simple/query_single.py --num_iter 1 --model_endpoint http://127.0.0.1:8000/${{ matrix.model }}"
          docker exec "${TARGET}" bash -c "python examples/inference/api_server_simple/query_single.py --num_iter 1 --model_endpoint http://127.0.0.1:8000/${{ matrix.model }} --streaming_response"

      - name: Run Inference Test with DeepSpeed
        run: |
          TARGET=${{steps.target.outputs.target}}
          if [[ ${{ matrix.model }} =~ ^(gpt2|mpt-7b.*)$ ]]; then
            echo ${{ matrix.model }} is not supported!
          else
            docker exec "${TARGET}" bash -c "python .github/workflows/config/update_inference_config.py --config_file inference/models/\"${{ matrix.model }}\".yaml --output_file \"${{ matrix.model }}\".yaml.deepspeed --deepspeed"
            docker exec "${TARGET}" bash -c "python inference/serve.py --config_file \"${{ matrix.model }}\".yaml.deepspeed --serve_simple"
            docker exec "${TARGET}" bash -c "python examples/inference/api_server_simple/query_single.py --num_iter 1 --model_endpoint http://127.0.0.1:8000/${{ matrix.model }}"
            docker exec "${TARGET}" bash -c "python examples/inference/api_server_simple/query_single.py --num_iter 1 --model_endpoint http://127.0.0.1:8000/${{ matrix.model }} --streaming_response"
          fi

      - name: Run Inference Test with DeepSpeed and Deltatuner
        if: ${{ matrix.dtuner_model }}
        run: |
          TARGET=${{steps.target.outputs.target}}
          if [[ ${{ matrix.model }} =~ ^(gpt2|mpt-7b.*)$ ]]; then
            echo ${{ matrix.model }} is not supported!
          else
            docker exec "${TARGET}" bash -c "python inference/serve.py --config_file .github/workflows/config/mpt_deltatuner_deepspeed.yaml --serve_simple"
            docker exec "${TARGET}" bash -c "python examples/inference/api_server_simple/query_single.py --num_iter 1 --model_endpoint http://127.0.0.1:8000/${{ matrix.model }}"
            docker exec "${TARGET}" bash -c "python examples/inference/api_server_simple/query_single.py --num_iter 1 --model_endpoint http://127.0.0.1:8000/${{ matrix.model }} --streaming_response"
          fi
      
      - name: Run Inference Test with REST API
        run: |
          TARGET=${{steps.target.outputs.target}}
          if [[ ${{ matrix.model }} == "mpt-7b-bigdl" ]]; then
            docker exec "${TARGET}" bash -c "python inference/serve.py --config_file inference/models/bigdl/mpt-7b-bigdl.yaml"
          else
            docker exec "${TARGET}" bash -c "MODEL_TO_SERVE=\"${{ matrix.model }}\" python inference/serve.py"
          fi
          docker exec "${TARGET}" bash -c "MODEL_TO_SERVE=\"${{ matrix.model }}\" python examples/inference/api_server_openai/query_http_requests.py"

      - name: Stop Ray
        run: |
          TARGET=${{steps.target.outputs.target}}
          cid=$(docker ps -q --filter "name=${TARGET}")
          if [[ ! -z "$cid" ]]; then
            docker exec "${TARGET}" bash -c "ray stop"
          fi
      
      - name: Stop Container
        if: success() || failure()
        run: |
          TARGET=${{steps.target.outputs.target}}
          cid=$(docker ps -q --filter "name=${TARGET}")
          if [[ ! -z "$cid" ]]; then docker stop $cid && docker rm $cid; fi

      - name: Test Summary
        run: echo "to be continued"


      
